//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Steven.Domain.Enums;
using Steven.Domain.Infrastructure;
using Dapper.Contrib.Extensions;
using System.ComponentModel.DataAnnotations;

namespace Steven.Domain.Models
{
    [Table("UserRole2Menu")]
    public class UserRole2Menu : AggregateRoot
    {
        public virtual long RoleId
        {
            get;
            set;
        }

        public virtual long MenuId
        {
            get;
            set;
        }

        [MaxLength(250)]
        public virtual string DisallowField
        {
            get;
            set;
        }

        public virtual string FilterGroups
        {
            get;
            set;
        }

        public SysButton Buttons { get; set; }

    }

    

}