//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Steven.Domain.Enums;
using Steven.Domain.Infrastructure;
using Dapper.Contrib.Extensions;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Steven.Domain.Models
{
    [Table("Users")]
    public partial class Users : AggregateRoot
    {
        [DisplayName("登录名")]
        [MaxLength(50)]
        [Required]
        public virtual string LoginName
        {
            get;
            set;
        }

        [DisplayName("密码")]
        [MaxLength(250)]
        [Required]
        public virtual string Password
        {
            get;
            set;
        }

        [DisplayName("密码盐")]
        [MaxLength(250)]
        [Required]
        public virtual string PasswordSalt
        {
            get;
            set;
        }

        [DisplayName("真实姓名")]
        [MaxLength(50)]
        public virtual string RealName
        {
            get;
            set;
        }

        [DisplayName("备注")]
        [MaxLength(250)]
        public virtual string Remark
        {
            get;
            set;
        }

        [DisplayName("登录次数")]
        public virtual int LoginCount
        {
            get;
            set;
        }

        [DisplayName("头像")]
        public virtual long HeadImageId { get; set; }

        [DisplayName("性别，0:保密;1:男;2:女")]
        public virtual Gender Gender { get; set; }

        [DisplayName("邮箱")]
        [MaxLength(100)]
        public string Email { get; set; }

        [DisplayName("加入方式")]
        public UserJoinWay JoinWay { get; set; }

        [DisplayName("设备号")]
        [StringLength(200)]
        public string DeviceCode { get; set; }

        [DisplayName("所属平台")]
        public UserPaltForm PaltForm { get; set; }

        [Display(Name = "极光注册号")]
        [StringLength(200)]
        public string JPushRegId { get; set; }

        public UserGroup UserGroup { get; set; }
        public CommonStatus CommonStatus { get; set; }
    }

}