//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Steven.Domain.Infrastructure;
using Dapper.Contrib.Extensions;

namespace Steven.Domain.Models
{
    [Table("User2Apartment")]
    public class User2Apartment : AggregateRoot
    {
        public virtual long UserId
        {
            get;
            set;
        }

        public virtual long ApartmentId
        {
            get;
            set;
        }

    }

}